[package]
name = "zed-sqls-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/sqls.rs"
[dependencies]
serde_json = "1.0.149"
serde_yml = "0.0.12"
zed_extension_api = "0.7.0"
