id = "sqls"
name = "SQLS"
description = "Language Server Protocol support for SQL using sqls"
version = "0.1.0"
schema_version = 1
authors = ["Mr_Tomate  <mrtomate360@outlook.com>"]
repository = "https://github.com/MrTomatePNG/zed-sqls-extension.git"

[grammars.sql]
repository = "https://github.com/DerekStride/tree-sitter-sql"
commit = "..."

[language_servers.sqls]
name = "sqls"
languages = ["SQL"]
